version: "3.9"

services:
  db:
    image: postgres:16
    container_name: volleyball_db
    env_file:
      - ../.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: volleyball_backend
    env_file:
      - ../.env.dev
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT:-8001}:8000"
    volumes:
      - ../backend:/app

  miniapp:
    build:
      context: ../miniapp-frontend
      dockerfile: Dockerfile
    container_name: volleyball_miniapp
    env_file:
      - ../.env.dev
    ports:
      - "8081:80"

  admin:
    build:
      context: ../admin-frontend
      dockerfile: Dockerfile
    container_name: volleyball_admin
    env_file:
      - ../.env.dev
    ports:
      - "8082:80"

volumes:
  postgres_data:
